config/routes.rb
Rails.application.routes.draw do

  resources :auctions
  resources :users
  resources :bids
  get '/' => "site#home"
  
end

app/models/auction.rb
class Auction < ActiveRecord::Base
	has_many :bids
	has_many :users, through: :bids

	validates :name, presence: true, length: { maximum: 30 }
	validates :end_date, presence: true

	validate :proper_date


		def assign_winner
			self.update_attribute :winner_id, self.bids.last.user_id
		end

		def price_sold
			self.update_attribute :end_price, self.bids.last.amount
		end

		def total_bids
			self.update_attribute :total_bid_num, self.bids.size
		end

	private
		def proper_date
			if end_date < Date.today
				errors.add( :end_date, "You're not Marty McFly, put a future date")
			end
		end

end

# FECHA , PUJAS MAS ALTA que actual para aceptar puja

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :auction #singular
	belongs_to :user

	validates :amount, numericality: true

	validate :proper_amount


	private
		def proper_amount
		# Conditionals -if with -any act like -Unless conditionals
		#Create this because when we create a auction,
		# this have no amount field, this is only created when we bids 
		if Auction.find(auction_id).bids.any?
			last_bid = Auction.find(auction_id).bids.last.amount
		else
			last_bid = 0
		end
			if amount <= last_bid
				errors.add(:amount, "Bid more")
			end
		end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :bids
	has_many :auctions, through: :bids

	validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
	validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

	def index
		@auctions = Auction.all.where("end_date > ?",Date.today) 
	end

	def new
		@auction = Auction.new
	end

	def create
		@auction = Auction.new auction_params

		if @auction.save
			redirect_to action: 'index'
		else
			render 'new'
		end
	end

	def show
		@auction = Auction.find params[:id]
		@users = User.all
		@bid = Bid.new
	end

	def destroy
		@auction = Auction.find params[:id]
		@auction.destroy
		redirect_to action: 'index'
	end

	private
	def auction_params
		params.require(:auction).permit(:name, :end_date)
	end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

	def create
		@bid = Bid.new bid_params
		@bid.save
		
		redirect_to auction_path(@bid.auction_id)
	end

	private
	def bid_params
		params.require(:bid).permit(:auction_id, :user_id, :amount)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def show
		@user = User.find params[:id]
	end

	def edit
		@user = User.find params[:id]
	end

	def update
		@user = User.find params[:id]
		@user.update_attributes user_params
		if @user.save
			redirect_to user_path(@user.id)
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find params[:id]
		@user.destroy
		redirect_to users_path
	end

	private
	def user_params
		params.require(:user).permit(:name, :email)	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/index.html.erb
<p>Hello</p>

<ul class="auction_list">
	<% @auctions.each do |auction| %>
		<li class="auction_item">
			<span><%= link_to(auction.name, auction_path(auction.id)) %></span>
		</li>
	<% end %>
</ul>


<%= link_to("+New aution", new_auction_path) %>

app/views/auctions/new.html.erb
<%= form_for @auction do |f| %>
	<fieldset>
		<legend>Create your auction now it's easier than ever</legend>
		<div class="form_field">
			<%= f.label :name %>
			<%= f.text_field :name, placeholder: "Auction name" %>
		</div>
		<div class="form_field">
			<%= f.label "End auction date" %>
			<%= f.date_field :end_date %>
		</div>
		<div class="form_field">
		<%= f.submit 'Publish Auction' %>
		</div>
	</fieldset>
<% end %>

app/views/auctions/show.html.erb
<h2><%= @auction.name %></h2>
<p><span><%= @auction.end_date %></span></p>


<!-- If fuction to check if the auction is still available and show the form -->

<%= form_for @bid do |f| %>
	<%= f.hidden_field :auction_id, value: @auction.id %>
	<fieldset>
		<legend>Bids now for this item</legend>
		<div class="form_field">
			<%= f.label "User to BId" %>
			<%= f.select(:user_id, options_for_select(@users.map { |user| [user.name, user.id] })) %>
		</div>
		<div class="form_field">
			<%= f.label "€" %>
			<%= f.number_field :amount, placeholder: "99,99" %>
		</div>
		<%= f.submit 'Save bid' %>
	</fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionsWebApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav>
		<ul>
			<li class="">Home</li>
			<li class=""><%= link_to("Subastas", auctions_path) %></li>
			<li class=""><%= link_to("Usuarios", users_path) %></li>
			<li class="">Contacto</li>
		</ul>
	</nav>
	<header class="header--top">
		<h1>Welcome to the AuctionsWebApp</h1>
		<h2>Hope you can find here what you are looking for</h2>
	</header>
	
	<section class="main-content">
		<%= yield %>
	</section>
	<aside>
		<!-- Here the sidebar. -->
	</aside>
</body>
</html>

app/views/site/home.html.erb
<h2> HOME PAGE </h2>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<fieldset>
		<legend>Register now and get premium access</legend>
		<div class="form_field">
			<%= f.label :name %>
			<%= f.text_field :name, placeholder: "Name" %>
		</div>
		<div class="form_field">
			<%= f.label :email %>
			<%= f.email_field :email, placeholder: "example@mail.com" %>
		</div>
		<div class="form_field">
		<%= f.submit 'Sign in' %>
		</div>
	</fieldset>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<ul>
	<% @users.each do |user| %>
	<li>
		<h4><%= user.name %></h4>
		<p><%= user.email %></p>
	</li>
	<% end %>
</ul>


<%= link_to("+Join now and start bid", new_user_path) %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<p><span><%= @user.email %></span></p>

<article>
	<h3>Pujas ganadas</h3>
	
</article>